### ISSUE TITLE
node php-server.js:Socket is not writable?

### ISSUE THREAD

**Issue by nroe** [billywhizz/node-fastcgi-parser#2]
my nginx connect php-fpm is ok.
plz help
# cat /opt/local/etc/nginx/nginx.conf

....
    upstream php-fpm {
         server 127.0.0.1:9000 weight=1;
   }
...
# node test-fastcgi.js 'true' 1 9000 '127.0.0.1'

{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'Socket is not writable' }
{"stack":"Error: EPIPE, Broken pipe\n    at Socket._writeImpl (net.js:159:14)\n    at Socket._writeOut (net.js:449:25)\n    at Socket.write (net.js:378:17)\n    at sendRequest (/Users/Nroe/Desktop/workspaces/node/davidcoallier-node-php-98c2340/test-fastcgi.js:100:14)\n    at Parser.onHeader (/Users/Nroe/Desktop/workspaces/node/davidcoallier-node-php-98c2340/test-fastcgi.js:164:6)\n    at Parser.execute (/Users/Nroe/Desktop/workspaces/node/davidcoallier-node-php-98c2340/lib/fastcgi.js:153:17)\n    at Socket.ondata (/Users/Nroe/Desktop/workspaces/node/davidcoallier-node-php-98c2340/test-fastcgi.js:140:10)\n    at Socket._onReadable (net.js:678:27)\n    at IOWatcher.onReadable [as callback](net.js:177:10)","message":"EPIPE, Broken pipe","errno":32,"code":"EPIPE","syscall":"write"}
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'Socket is not writable' }
{"stack":"Error: EPIPE, Broken pipe\n    at Socket._writeImpl (net.js:159:14)\n    at Socket._writeOut (net.js:449:25)\n    at Socket.write (net.js:378:17)\n    at sendRequest (/Users/Nroe/Desktop/workspaces/node/davidcoallier-node-php-98c2340/test-fastcgi.js:100:14)\n    at Parser.onHeader (/Users/Nroe/Desktop/workspaces/node/davidcoallier-node-php-98c2340/test-fastcgi.js:164:6)\n    at Parser.execute (/Users/Nroe/Desktop/workspaces/node/davidcoallier-node-php-98c2340/lib/fastcgi.js:153:17)\n    at Socket.ondata (/Users/Nroe/Desktop/workspaces/node/davidcoallier-node-php-98c2340/test-fastcgi.js:140:10)\n    at Socket._onReadable (net.js:678:27)\n    at IOWatcher.onReadable [as callback](net.js:177:10)","message":"EPIPE, Broken pipe","errno":32,"code":"EPIPE","syscall":"write"}

**Comment by billywhizz** [comment]
This isn't an issue with my parser. all it does is parse data and raise events. It looks like the error is happening on line 164 of the test-fastcgi.js script you are using. It is in the onHeader handler and i presume from the EPIPE error you are attempting to write to a connection that is broken. You should have a try/catch around the socket write in that script and end the connection if you get an EPIPE.

**Comment by samcday** [comment]
@nroe

What billywhizz said. 

Just to add though, if you're getting a broken pipe it generally means the other end processed your record and didn't like it, so it closed the connection. This could be from malformed/invalid/missing data, so you need to recheck everything you're sending down the line (and the order etc) to make sure its conforming to the FCGI spec.

Sorry to hijack your issue Andrew :)
